### ISSUE TITLE
Data Feed Delete

### ISSUE THREAD

**Issue by ashishodia** [googleads/googleads-shopping-samples#7]
Hi Team,

We are building an application where we using the python API for managing the Merchant Account. We have used the datafeed_delete.py for deleting the data feeds and also using datafeed_insert.py API for inserting the feeds.

However, we are seeing some product IDs in our merchant account which are coming from the deleted feeds (the feeds that had been deleted through datafeed_delete.py). 

Is there any delay in deleting the product using API and how much time it is taking to remove the product from previous feeds or any issue over there.?

Many thanks for your support in advance.

**Comment by ashishodia** [comment]
Hey Team ....Any update on this?

**Comment by sstrickl** [comment]
Hi @ashishodia, sorry about the long delay in responding to this.  Are you still seeing this issue?

Also, for questions like this, the [Google Content API for Shopping](https://groups.google.com/forum/#!forum/google-content-api-for-shopping) Google group is probably a better place to ask, as we have dedicated support people there for quickly responding to queries.  It'd be best to keep the focus here on questions/feedback on the samples themselves, not on the working behavior of the API in general.
